// <auto-generated />
using System;
using ClinicNext.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicNext.Api.Data.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20260613092433_FixRolesIdentitySequence")]
    partial class FixRolesIdentitySequence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.AlkesDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Harga")
                        .HasColumnType("numeric")
                        .HasColumnName("harga");

                    b.Property<long>("IdAlkes")
                        .HasColumnType("bigint")
                        .HasColumnName("id_alkes");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<int>("Jumlah")
                        .HasColumnType("integer")
                        .HasColumnName("jumlah");

                    b.Property<string>("KodeBarang")
                        .HasColumnType("text")
                        .HasColumnName("kode_barang");

                    b.Property<string>("NamaBarang")
                        .HasColumnType("text")
                        .HasColumnName("nama_barang");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("tt_alkes_detail", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.AlkesPelayananEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdAlkes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_alkes");

                    b.Property<string>("IdPasien")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tanggal")
                        .HasColumnType("text")
                        .HasColumnName("tanggal");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("tt_alkes", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.AsesmenMedisPasienRawatJalanEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_asesmen_medis_pasien_rawat_jalan", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.AsesmenMedisPasienSpesialisGigiRawatJalanEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_asesmen_medis_pasien_spesialis_gigi_rawat_jalan", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.BlankRekamMedisEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.Property<string>("RekamMedis")
                        .HasColumnType("text")
                        .HasColumnName("rekam_medis");

                    b.HasKey("Id");

                    b.ToTable("mr_blank_rekam_medis", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.CatatanPerkembanganPasienTerintegrasiEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_catatan_perkembangan_pasien_terintegrasi", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.DiagnosaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KodeDiagnosa")
                        .HasColumnType("text")
                        .HasColumnName("kode_diagnosa");

                    b.Property<string>("KodeSnomed")
                        .HasColumnType("text")
                        .HasColumnName("kode_snomed");

                    b.Property<string>("NamaDiagnosa")
                        .HasColumnType("text")
                        .HasColumnName("nama_diagnosa");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("tm_diagnosa", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.DokterEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("KdDokter")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("NamaDokter")
                        .HasColumnType("text")
                        .HasColumnName("nm_dokter");

                    b.HasKey("Id");

                    b.ToTable("tm_dokter", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.JasaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("Harga")
                        .HasColumnType("numeric")
                        .HasColumnName("harga");

                    b.Property<string>("Icd9")
                        .HasColumnType("text")
                        .HasColumnName("icd9");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text")
                        .HasColumnName("keterangan");

                    b.Property<string>("NamaJasa")
                        .HasColumnType("text")
                        .HasColumnName("nama_jasa");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("tm_jasa", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.KodePosEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Kabupaten")
                        .HasColumnType("text")
                        .HasColumnName("kabupaten");

                    b.Property<string>("Kecamatan")
                        .HasColumnType("text")
                        .HasColumnName("kecamatan");

                    b.Property<string>("Kelurahan")
                        .HasColumnType("text")
                        .HasColumnName("kelurahan");

                    b.Property<string>("KodePos")
                        .HasColumnType("text")
                        .HasColumnName("kode_pos");

                    b.Property<string>("Provinsi")
                        .HasColumnType("text")
                        .HasColumnName("provinsi");

                    b.HasKey("Id");

                    b.ToTable("tm_kode_pos", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.KodeWilayahEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("KodeBps")
                        .HasColumnType("text")
                        .HasColumnName("kode_bps");

                    b.Property<string>("KodeLama")
                        .HasColumnType("text")
                        .HasColumnName("kode_lama");

                    b.Property<string>("KodeWilayah")
                        .HasColumnType("text")
                        .HasColumnName("kode_wilayah");

                    b.Property<string>("NamaWilayah")
                        .HasColumnType("text")
                        .HasColumnName("nama_wilayah");

                    b.Property<string>("Parent")
                        .HasColumnType("text")
                        .HasColumnName("parent");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("tm_kode_wilayah", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.LaboratoriumDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Harga")
                        .HasColumnType("numeric")
                        .HasColumnName("harga");

                    b.Property<string>("Hasil")
                        .HasColumnType("text")
                        .HasColumnName("hasil");

                    b.Property<long>("IdLaboratorium")
                        .HasColumnType("bigint")
                        .HasColumnName("id_laboratorium");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<int>("Jumlah")
                        .HasColumnType("integer")
                        .HasColumnName("jumlah");

                    b.Property<string>("KodePemeriksaan")
                        .HasColumnType("text")
                        .HasColumnName("kode_pemeriksaan");

                    b.Property<string>("NamaPemeriksaan")
                        .HasColumnType("text")
                        .HasColumnName("nama_pemeriksaan");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("tt_laboratorium_detail", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.LaboratoriumEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdLaboratorium")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_laboratorium");

                    b.Property<string>("IdPasien")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tanggal")
                        .HasColumnType("text")
                        .HasColumnName("tanggal");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("tt_laboratorium", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.PasienEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Agama")
                        .HasColumnType("text")
                        .HasColumnName("agama");

                    b.Property<string>("Alamat")
                        .HasColumnType("text")
                        .HasColumnName("alamat");

                    b.Property<string>("Day")
                        .HasColumnType("text")
                        .HasColumnName("day");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("IdIhs")
                        .HasColumnType("text")
                        .HasColumnName("id_ihs");

                    b.Property<string>("IdPasien")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("JenisKelamin")
                        .HasColumnType("text")
                        .HasColumnName("jenis_kelamin");

                    b.Property<string>("Kecamatan")
                        .HasColumnType("text")
                        .HasColumnName("kecamatan");

                    b.Property<string>("Kelurahan")
                        .HasColumnType("text")
                        .HasColumnName("kelurahan");

                    b.Property<string>("KodePos")
                        .HasColumnType("text")
                        .HasColumnName("kode_pos");

                    b.Property<string>("Kota")
                        .HasColumnType("text")
                        .HasColumnName("kota");

                    b.Property<string>("Month")
                        .HasColumnType("text")
                        .HasColumnName("month");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nik");

                    b.Property<string>("NoHp")
                        .HasColumnType("text")
                        .HasColumnName("no_hp");

                    b.Property<string>("Npwp")
                        .HasColumnType("text")
                        .HasColumnName("npwp");

                    b.Property<string>("Pekerjaan")
                        .HasColumnType("text")
                        .HasColumnName("pekerjaan");

                    b.Property<string>("Provinsi")
                        .HasColumnType("text")
                        .HasColumnName("provinsi");

                    b.Property<string>("Rt")
                        .HasColumnType("text")
                        .HasColumnName("rt");

                    b.Property<string>("Rw")
                        .HasColumnType("text")
                        .HasColumnName("rw");

                    b.Property<string>("StatusKawin")
                        .HasColumnType("text")
                        .HasColumnName("status_kawin");

                    b.Property<string>("Year")
                        .HasColumnType("text")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("tm_pasien", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.PembayaranDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("IdPembayaran")
                        .HasColumnType("bigint")
                        .HasColumnName("id_pembayaran");

                    b.Property<string>("Item")
                        .HasColumnType("text")
                        .HasColumnName("item");

                    b.Property<string>("KodeItem")
                        .HasColumnType("text")
                        .HasColumnName("kode_item");

                    b.Property<decimal>("Nominal")
                        .HasColumnType("numeric")
                        .HasColumnName("nominal");

                    b.HasKey("Id");

                    b.ToTable("tt_pembayaran_detail", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.PembayaranEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BAdmin")
                        .HasColumnType("numeric")
                        .HasColumnName("b_admin");

                    b.Property<decimal?>("BOngkir")
                        .HasColumnType("numeric")
                        .HasColumnName("b_ongkir");

                    b.Property<decimal?>("BTambahan")
                        .HasColumnType("numeric")
                        .HasColumnName("b_tambahan");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("Diskon")
                        .HasColumnType("numeric")
                        .HasColumnName("diskon");

                    b.Property<decimal?>("Grandtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("grandtotal");

                    b.Property<string>("IdPasien")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<decimal?>("JumlahBayar")
                        .HasColumnType("numeric")
                        .HasColumnName("jumlah_bayar");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("NoInvoice")
                        .HasColumnType("text")
                        .HasColumnName("no_invoice");

                    b.Property<decimal?>("Sisa")
                        .HasColumnType("numeric")
                        .HasColumnName("sisa");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TglBayar")
                        .HasColumnType("text")
                        .HasColumnName("tgl_bayar");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("tt_pembayaran", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.PendaftaranEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("IdPasien")
                        .HasColumnType("bigint")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tanggal")
                        .HasColumnType("text")
                        .HasColumnName("tanggal");

                    b.HasKey("Id");

                    b.ToTable("tt_pendaftaran", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.PengeluaranDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Biaya")
                        .HasColumnType("numeric")
                        .HasColumnName("biaya");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Jumlah")
                        .HasColumnType("integer")
                        .HasColumnName("jumlah");

                    b.Property<string>("Nama")
                        .HasColumnType("text")
                        .HasColumnName("nama");

                    b.Property<long>("PengeluaranId")
                        .HasColumnType("bigint")
                        .HasColumnName("pengeluaran_id");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("sub_total");

                    b.HasKey("Id");

                    b.ToTable("tt_pengeluaran_detail", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.PengeluaranEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("File")
                        .HasColumnType("text")
                        .HasColumnName("file");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("grand_total");

                    b.Property<string>("InputBy")
                        .HasColumnType("text")
                        .HasColumnName("input_by");

                    b.Property<int?>("IsAktif")
                        .HasColumnType("integer")
                        .HasColumnName("is_aktif");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text")
                        .HasColumnName("keterangan");

                    b.Property<string>("KodePengeluaran")
                        .HasColumnType("text")
                        .HasColumnName("kode_pengeluaran");

                    b.Property<string>("Tanggal")
                        .HasColumnType("text")
                        .HasColumnName("tanggal");

                    b.HasKey("Id");

                    b.ToTable("tt_pengeluaran", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.RadiologiDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Harga")
                        .HasColumnType("numeric")
                        .HasColumnName("harga");

                    b.Property<string>("Hasil")
                        .HasColumnType("text")
                        .HasColumnName("hasil");

                    b.Property<long>("IdRadiologi")
                        .HasColumnType("bigint")
                        .HasColumnName("id_radiologi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<int>("Jumlah")
                        .HasColumnType("integer")
                        .HasColumnName("jumlah");

                    b.Property<string>("KodePemeriksaan")
                        .HasColumnType("text")
                        .HasColumnName("kode_pemeriksaan");

                    b.Property<string>("NamaPemeriksaan")
                        .HasColumnType("text")
                        .HasColumnName("nama_pemeriksaan");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("tt_radiologi_detail", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.RadiologiEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRadiologi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_radiologi");

                    b.Property<string>("IdRegistrasi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tanggal")
                        .HasColumnType("text")
                        .HasColumnName("tanggal");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("tt_radiologi", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("tt_auth_refresh_token", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.RekamMedisHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<long?>("IdRm")
                        .HasColumnType("bigint")
                        .HasColumnName("id_rm");

                    b.Property<string>("Jam")
                        .HasColumnType("text")
                        .HasColumnName("jam");

                    b.Property<string>("JudulRm")
                        .HasColumnType("text")
                        .HasColumnName("judul_rm");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.Property<string>("Tanggal")
                        .HasColumnType("text")
                        .HasColumnName("tanggal");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("tt_rekam_medis_history", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.ResepDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AturanPakai")
                        .HasColumnType("text")
                        .HasColumnName("aturan_pakai");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Harga")
                        .HasColumnType("numeric")
                        .HasColumnName("harga");

                    b.Property<string>("IdBarang")
                        .HasColumnType("text")
                        .HasColumnName("id_barang");

                    b.Property<long>("IdResep")
                        .HasColumnType("bigint")
                        .HasColumnName("id_resep");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<int>("Jumlah")
                        .HasColumnType("integer")
                        .HasColumnName("jumlah");

                    b.Property<string>("NamaObat")
                        .HasColumnType("text")
                        .HasColumnName("nama_obat");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("tt_resep_detail", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.ResepEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<string>("IdResep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_resep");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("Racikan")
                        .HasColumnType("text")
                        .HasColumnName("racikan");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tanggal")
                        .HasColumnType("text")
                        .HasColumnName("tanggal");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("tt_resep", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.RolePermissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Allowed")
                        .HasColumnType("boolean")
                        .HasColumnName("allowed");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permission_key");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "PermissionKey")
                        .IsUnique();

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SettingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Alamat")
                        .HasColumnType("text")
                        .HasColumnName("alamat");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("InputBy")
                        .HasColumnType("text")
                        .HasColumnName("input_by");

                    b.Property<string>("Jenis")
                        .HasColumnType("text")
                        .HasColumnName("jenis");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text")
                        .HasColumnName("keterangan");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("LogoSidebar")
                        .HasColumnType("text")
                        .HasColumnName("logo_sidebar");

                    b.Property<string>("Nama")
                        .HasColumnType("text")
                        .HasColumnName("nama");

                    b.Property<string>("NoHp")
                        .HasColumnType("text")
                        .HasColumnName("no_hp");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("TaxId")
                        .HasColumnType("text")
                        .HasColumnName("tax_id");

                    b.Property<string>("TitleSidebar")
                        .HasColumnType("text")
                        .HasColumnName("title_sidebar");

                    b.HasKey("Id");

                    b.ToTable("tm_setting", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.StandartFieldEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DescField")
                        .HasColumnType("text")
                        .HasColumnName("desc_field");

                    b.Property<string>("File")
                        .HasColumnType("text")
                        .HasColumnName("file");

                    b.Property<long?>("IdFieldGroup")
                        .HasColumnType("bigint")
                        .HasColumnName("id_fieldgroup");

                    b.Property<int?>("IsAktif")
                        .HasColumnType("integer")
                        .HasColumnName("is_aktif");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text")
                        .HasColumnName("keterangan");

                    b.Property<string>("KodeField")
                        .HasColumnType("text")
                        .HasColumnName("kode_field");

                    b.HasKey("Id");

                    b.ToTable("tm_standartfield", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.StandartFieldGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("IsAktif")
                        .HasColumnType("integer")
                        .HasColumnName("is_aktif");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text")
                        .HasColumnName("keterangan");

                    b.Property<string>("Nama")
                        .HasColumnType("text")
                        .HasColumnName("nama");

                    b.Property<string>("Tanggal")
                        .HasColumnType("text")
                        .HasColumnName("tanggal");

                    b.HasKey("Id");

                    b.ToTable("tm_standartfield_group", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SuratJawabanKonsultasiEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_surat_jawaban_konsultasi", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SuratKeteranganSakitEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_surat_keterangan_sakit", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SuratKeteranganSehatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_surat_keterangan_sehat", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SuratKonsultasiEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_surat_konsultasi", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SuratKontrolEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_surat_kontrol", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SuratPenolakanTindakanKedokteranEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_surat_penolakan_tindakan_kedokteran", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SuratPermintaanDirawatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_surat_permintaan_dirawat", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SuratPermintaanODCEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_surat_permintaan_odc", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SuratPermintaanTindakanEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_surat_permintaan_tindakan", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SuratPersetujuanTindakanKedokteranEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_surat_persetujuan_tindakan_kedokteran", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.SuratRingkasanPasienPulangEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("KodeRm")
                        .HasColumnType("text")
                        .HasColumnName("kode_rm");

                    b.HasKey("Id");

                    b.ToTable("mr_surat_ringkasan_pasien_pulang", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.TindakanDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<decimal>("Harga")
                        .HasColumnType("numeric")
                        .HasColumnName("harga");

                    b.Property<long>("IdJasa")
                        .HasColumnType("bigint")
                        .HasColumnName("id_jasa");

                    b.Property<long>("IdTindakan")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tindakan");

                    b.Property<int>("Jumlah")
                        .HasColumnType("integer")
                        .HasColumnName("jumlah");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("tt_tindakan_detail", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.TindakanEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IdPasien")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_pasien");

                    b.Property<string>("IdRegistrasi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_registrasi");

                    b.Property<string>("IdTransaksi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_transaksi");

                    b.Property<int?>("InputBy")
                        .HasColumnType("integer")
                        .HasColumnName("input_by");

                    b.Property<string>("KdDokter")
                        .HasColumnType("text")
                        .HasColumnName("kd_dokter");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Tanggal")
                        .HasColumnType("text")
                        .HasColumnName("tanggal");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.ToTable("tt_tindakan", (string)null);
                });

            modelBuilder.Entity("ClinicNext.Api.Domain.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("RememberToken")
                        .HasColumnType("text")
                        .HasColumnName("remember_token");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
